// module.exports = [
// 	'fun-news',
// 	'society-science',
// 	'arm-electronic',
// 	'entertainment-music',
// 	'media-video',
// 	'spa-beauty',
// 	'painting',
// 	'medicine',
// 	'art-sports',
// 	'marriage-relationship',
// 	'education-child',
// 	'men-women'
// ]


module.exports = [	'news', 
					'videos', 
					'rent', 
					'askForRent',
					'agent-rent', 
					'house', 
					'hire', 
					'sales-hire', 
					'restaurant-hire', 
					'salon-hire', 
					'massage-hire', 
					'apply', 
					'commercial-rent', 
					'business', 
					'delivery',
					'mortgage',
					'second-hand',
					'cars',
					'phones',
					'computers',
					'products',
					'internet',
					'security',
					'spa',
					'massage',
					'network',
					'find',
					'translation',
					'training',
					'academy',
					'preschool',
					'moving',
					'cab',
					'driving-school',
					'hotel',
					'others',
					'insurance',
					'abroad',
					'citizenship',
					'law',
					'accounting',
					'print',
					'decoration',
					'utility',
					'construction'
				]